### ISSUE TITLE
replace `log` with `tracing` ?

### ISSUE THREAD

**Issue by jondot** [epwalsh/rust-cached-path#62]
Hi,
Thanks for this library, I'm using it and really enjoying the interface!
Wondering if you're considering moving to tracing instead of log? it could provide more visibility, especially for this kind of scenario where you have network requests, cache, disk access, etc.
If so, I feel that I could take a stab at it.

**Comment by epwalsh** [comment]
Hey @jondot, thanks for the kind words 🙂 I'm always happy to hear that someone is using this little library.

Tracing would be great! I did consider it before but it fell off my radar due to other priorities, so I'd love to review a PR if you want to tackle it.

**Comment by jondot** [comment]
great! I'll add that to my to-do list :)
on a side note - I found the progress-bar wrapping which makes it `Write` really clever, so much that I think it can be it's own library, but -- one step at a time :)

**Comment by jondot** [comment]
This actually works out of the box for me (my host app uses tracing, and I see logs from `rust-cached-path` appearing in traces as events)
So I'll close this one :)
