### ISSUE TITLE
Cleanup implemented?

### ISSUE THREAD

**Issue by jondot** [epwalsh/rust-cached-path#63]
Hi,
I tried looking at a few places, but looks like cleanup isn't implemented, but it's mentioned here:

https://github.com/epwalsh/rust-cached-path/blob/main/src/cache.rs#L387-L388

Is there anything I might be missing?

**Comment by epwalsh** [comment]
Oh, that comment is misleading and should be changed. I decided against automatic cache eviction for safety reasons.
